spring:
  profiles.active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: 'GreenfieldHealth'

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/greenfield_health
    username: postgres
    password: 123456

  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: create-drop

  banner.location: banner.txt

server.port: 8080
